sudo: required
language: java
jdk:
  - oraclejdk8
branches:
 only:
  - master
before_install:
  - sudo apt-get install jq
  - wget -O ~/codacy-coverage-reporter-assembly-latest.jar $(curl https://api.github.com/repos/codacy/codacy-coverage-reporter/releases/latest | jq -r .assets[0].browser_download_url)
install: ./gradlew clean build
script: ./gradlew test jacocoTestReport jacocoFullReport
after_success:
  - java -cp ~/codacy-coverage-reporter-assembly-latest.jar com.codacy.CodacyCoverageReporter -l Java -r build/reports/jacoco/fullReport.xml
